### ISSUE TITLE
Proper handling of tokens

### ISSUE THREAD

**Issue by nanosonde** [grm/py-smart-gardena#23]
Are you aware of [this API description](https://developer.1689.cloud/apis/Authentication+API#/readme) from Husqvarna?

In your code I can only see a HTTP POST request to get the session token (accessToken) for accessing the REST API.
However, you are never invalidating the token again as described in the documentation. Invalidating basically means "logout". If you never logout you might hit the mentioned security limits and the app on a mobile device does not work properly. You have to logout and login again, because the maximum number of tokens limit was hit. 

Other software projects seems to have similar [issues](https://github.com/openhab/openhab2-addons/issues/5815).

**Comment by grm** [comment]
Thank you Nanosonde for your report.

I was not aware of that. I will have a look into that ASAP.
It should be easy to implement I guess.

**Comment by grm** [comment]
Not so easy to adress.

Husqvarna release their API and breaks the old way of working.
I started a rewrite of the API to manage this new version.

**Comment by grm** [comment]
Hello,

I completely rewrite the library to use the new public gardena API.
And to do that, i added a function named 'quit()' which handles the logout from the system (smart_system.quit()). It is then up to the application that uses this library to call this method when it is suited.

This function can be found here : https://github.com/grm/py-smart-gardena/blob/master/src/gardena/smart_system.py#L108

Thank you for your report.
