### ISSUE TITLE
Plans regarding home-assistant

### ISSUE THREAD

**Issue by wijnandtop** [grm/py-smart-gardena#49]
Hi,

I'm the author of home_assistant_gardena, a component for integrating gardena within home assistant.
Unfortunately it is broken for a while now. Today I was investigating how to get it up to date including the underlying python library ( https://github.com/wijnandtop/wt.pygardena ) which was using an unofficial api which I reversed engineered. 

Part of updating the home_assistant component was rewriting the library using the official API. Then I ran into your lib which all-ready did most of the integration.

In your github profile I saw also a fork of home assistant. Are you allready working on integrating gardena into hass?
What are your plans?

If you are already working on it, maybe I can help. Having two projects working on this doesn't make sense (and your lib is way better).

**Comment by sfstar** [comment]
It seems that GRM has gone inactive.
His pull-request to home assistant has already been closed and remained so for over the last couple of months.
Furthermore, the (home assistant gardena component) current code base only seems to have a working implementation for the gardena mower.
I've submitted an pull-request https://github.com/grm/home-assistant/pull/1 to fix an bug that prevented activating the valves from home assistant.

However, for example state changes of valves, do not seem to work correctly as of yet.
Therefore, I'm assuming that some more troubleshooting / work needs to be done before this component can be submitted to home assistant.

I'm also willing to offer my assistance in improving GRM's home_assistant gardena component.
I would also like to reach out to you wijnandtop to collaborate on the gardena component for home assistant.
If GRM is unable continue his work on the gardena home-assistant component

**Comment by supernial** [comment]
Hey, can I participate in this. I think I can help here. Also I have time to push it further.

**Comment by wijnandtop** [comment]
Help is surely welcome, let's move this discussion towards https://github.com/wijnandtop/home_assistant_gardena/issues/18 and discuss how to proceed and join efforts.

**Comment by grm** [comment]
Hello,

sorry for the lag in the response.
I had busy weeks at work but now it should be better on my side.
I would be happy to rework on the project with other guys if you still agree to that.

Indeed, I made a PR to home assistant a few month ago, but they were some lags in their answer too (i can totally understand that :-). I then start a new job and had less time for this project.

Now i am baack on track, especially if there are some reinforcments :)

**Comment by wijnandtop** [comment]
Hey welcome back ;-)

Right now there are quite some forks of your implementation, the most vivid project is;
https://github.com/osks/hass-gardena-smart-system

Please join :-),  to catch up read: https://github.com/wijnandtop/home_assistant_gardena/issues/18

**Comment by grm** [comment]
Hello,

we decided with osks to work together on this implementation and thus create an organisation which can be found here : https://github.com/py-smart-gardena/

This organisation will be there to hold the code for both the python-smart-gardena library and the hass connector of osks.

Regards,
Jérémie
