### ISSUE TITLE
Error by  smart_system.update_locations()

### ISSUE THREAD

**Issue by Pol3cat** [grm/py-smart-gardena#54]
Hi grm,
since yesterday i got following error by starting this nice script.
Before yesterday it works without any problems....

Traceback (most recent call last):
  File "gardena_test.py", line 12, in <module>
    smart_system.update_locations()
  File "/usr/local/lib/python3.7/dist-packages/gardena/smart_system.py", line 156, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.7/dist-packages/gardena/smart_system.py", line 151, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.7/dist-packages/gardena/smart_system.py", line 144, in __response_has_errors
    f"{response.status_code} : {r['errors'][0]['title']} - {r['errors'][0]['detail']}"
KeyError: 'errors'

Did you get these errors too?

Thx

**Comment by silvermind** [comment]
I've the same issue, I assume they changes their rate limits. Using the debug mode with:

`smart_system = SmartSystem(email="XXX", password="XXX", client_id="XXX", level=logging.DEBUG)`

I get:
`DEBUG:urllib3.connectionpool:https://api.smart.gardena.dev:443 "GET /v1/locations HTTP/1.1" 429 = Too Many Requests`

Rate Limits: https://developer.1689.cloud/apis/GARDENA+smart+system+API#rate-limits
```
Rate limits are in place to prevent malicious use of the API that would impact other users.

Each application has the following limits:
- Throttling occurs if average call rate exceeds one call every fifteen minutes.
- Quota of 3'000 requests per month.
```

Not sure if the line "Throttling occurs if average call rate exceeds one call every fifteen minutes." was there before..

**Comment by Pol3cat** [comment]
When i use the websocket and a while loop it seems i can use more than 3000 requests.
Sometimes i got a lost connection...


`
#!/usr/bin/env python3


from gardena.smart_system import SmartSystem
import pprint
import time

LOCATION_ID = "xxx"

i = 0

smart_system = SmartSystem(email="xxx", password="xxx", client_id="xxx")
smart_system.authenticate()
smart_system.update_locations()




for location in smart_system.locations.values():
    smart_system.update_devices(location)
    pprint.pprint(location)
    for device in location.devices.values():
        pprint.pprint(device)

smart_system.start_ws(smart_system.locations[LOCATION_ID])        

while True:
    print()
    print(i)
    print()
    
    
    for device in smart_system.locations[LOCATION_ID].find_device_by_type("MOWER"):
       print(f"name : {device.name}")
       print(f"battery_level : {device.battery_level}")
       print(f"battery_state : {device.battery_state}")
       print(f"rf_link_level : {device.rf_link_level}")
    
    for device in smart_system.locations[LOCATION_ID].find_device_by_type("SENSOR"):
        print()
        print(f"name : {device.name}")       
        print(f"battery_level : {device.battery_level}")
        print(f"battery_state : {device.battery_state}")
        print(f"rf_link_level : {device.rf_link_level}")
        print(f"ambient_temperature : {device.ambient_temperature}")
        print(f"light_intensity : {device.light_intensity}")
        print(f"soil_humidity : {device.soil_humidity}")
        print(f"soil_temperature : {device.soil_temperature}")

    for device in smart_system.locations[LOCATION_ID].find_device_by_type("WATER_CONTROL"):
        print()
        print(f"name : {device.name}")

        print(f"battery_level : {device.battery_level}")
        print(f"battery_state : {device.battery_state}")
        print(f"rf_link_level : {device.rf_link_level}")

        print(f"valve_activity : {device.valve_activity}")
    
            
    time.sleep(5) 
    i=i+1
`

**Comment by grm** [comment]
Hello, 

I will have a look into this asap :)

Regards
Grm

**Comment by grm** [comment]
Hello,
you should use the websocket in order to get updates, to avoid hitting the limit of the API. This way, you keep a connection alive with the API and get updates pushed directly by the gardena API wehn a changes occurs.

the method to use is described here : 
https://github.com/py-smart-gardena/py-smart-gardena#using-websocket

you need to call this function : 
```
smart_system.start_ws(self._hass.data[DOMAIN][GARDENA_LOCATION])

```

By the way, we created an organisation to hold our open source code for both home asssitant and the library here : https://github.com/py-smart-gardena/

Issues should now be posted there !

If you still have the issue after using the websocket, feel free to open an issue there : https://github.com/py-smart-gardena/py-smart-gardena
